### PR TITLE
fix: camelcase option name before setting default value

### LINKED ISSUE #61: [Bug Report] Multiple words negated options
## Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

### Steps to repro

```js
// test.js
const cli = require('cac')();

cli.option('--no-aaa-bbb').option('--no-ccc');

const parsed = cli.parse();

console.log(JSON.stringify(parsed, null, 2));
```

```sh
$ node test.js
{
  "args": [],
  "options": {
    "--": [],
    "aaa-bbb": true,
    "ccc": true
  }
}

$ node test.js --no-aaa-bbb
{
  "args": [],
  "options": {
    "--": [],
    "aaa-bbb": true,
    "ccc": true,
    "aaaBbb": false
  }
}

$ node test.js --no-ccc
{
  "args": [],
  "options": {
    "--": [],
    "aaa-bbb": true,
    "ccc": false
  }
}
```

The `"aaa-bbb": true` is always there.

## Info

- CAC version: 6.5.3

### PR DESCRIPTION
**Pull request by egoist**
Closes #61

### CODE REVIEW

**Comment by vladimyr** [comment]
⚠️ @egoist I didn't do full research due to time constraints but this definitely broke `poi` (and possibly other CLIs using it). For instance, if you try to use any multiword option you'll get unknown option error:
```
$ npx poi --inspect-webpack
error: Unknown option `--inspect-webpack`
```

**Comment by egoist** [comment]
@vladimyr should be fixed in 6.5.5

**Comment by vladimyr** [comment]
egoist - the man and the legend ⚡️

**Pull request merged**
